name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  validate:
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-build-test.yml@main
    with:
      java-version: 21
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  
  spotless:
    needs: validate
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-spotless-check.yml@main
    with:
      java-version: 21

  license:
    needs: spotless
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-license-check.yml@main
    with:
      java-version: 21
      
  publish:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release' }}
    needs: license
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-publish.yml@main
    with:
      java-version: 21
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  docker-publish:
    needs: publish
    uses: mekomsolutions/shared-github-workflow/.github/workflows/docker-build-publish.yml@main
    with:
      download-artifacts: false
      image-name: "keycloak-active-users-exporter"
      image-version: "latest"
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}